export const ALL_ADFDATA_SUCESS = "ALL_ADFDATA_SUCESS" ;
export const ALL_ADFDATA_FAIL = "ALL_ADFDATA_FAIL" ;
export const ALL_ADFDATA_REQUEST = "ALL_ADFDATA_REQUEST" ;

export const ALL_ADFDATA_GET_SUCESS = "ALL_ADFDATA_GET_SUCESS" ;
export const ALL_ADFDATA_GET_FAIL = "ALL_ADFDATA_GET_FAIL" ;
export const ALL_ADFDATA_GET_REQUEST = "ALL_ADFDATA_GET_REQUEST" ;


export const CLEAR_ERROR = "CLEAR_ERROR" ;