export const All_VIFOMEDATAUPLOAD_REQUEST = "ALL_VIFOMEDATAUPLOAD_REQUEST";
export const All_VIFOMEDATAUPLOAD_SUCESS = "ALL_VIFOMEDATAUPLOAD_SUCESS";
export const All_VIFOMEDATAUPLOAD_FAIL = "ALL_VIFOMEDATAUPLOAD_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";